from __future__ import annotations
import json
from pathlib import Path
from . import schema_guard

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "SCHEMA.md"


def _fmt_props(props: dict, required: set) -> str:
    rows = ["| field | type | required | notes |", "|---|---|---|---|"]
    for name, spec in props.items():
        t = spec.get("type", spec.get("$ref", spec.get("const", "any")))
        req = "yes" if name in required else "no"
        notes = spec.get("description", "")
        if "enum" in spec:
            notes = (notes + " " if notes else "") + f"enum: {', '.join(map(str, spec['enum']))}"
        if "const" in spec:
            notes = (notes + " " if notes else "") + f"const: {spec['const']}"
        rows.append(f"| `{name}` | {t} | {req} | {notes} |")
    return "\n".join(rows)


def generate() -> str:
    schema = schema_guard.load_schema()
    lines = [
        "<!-- AUTO-GENERATED by gateway/docgen.py from schema/agent.schema.json. Do not hand-edit. -->",
        "# JetFighter Agent Schema Reference",
        "",
        f"Schema version: `{schema['properties']['meta']['properties']['schema_version']['const']}`",
        "",
        "Every request/response is one JSON object validated against `schema/agent.schema.json`. "
        "`additionalProperties: false` is set on every object in this schema, so any unknown field "
        "is a hard rejection, not a warning.",
        "",
        "## Top-level shape",
        "",
        "| section | required | purpose |",
        "|---|---|---|",
        "| `meta` | yes | session/versioning envelope |",
        "| `intent` | yes | what action, on what domain, at what priority |",
        "| `payload` | yes | the action-specific data |",
        "| `response` | no (server-filled) | filled in by `gateway/gateway.py`, itself schema-validated before being returned |",
        "",
        "## intent.action (enum)",
        "",
    ]
    actions = schema["properties"]["intent"]["properties"]["action"]["enum"]
    from . import handlers
    for a in actions:
        handled = "handled" if a in handlers.DISPATCH else "**NO HANDLER REGISTERED**"
        lines.append(f"- `{a}` — {handled}")

    lines += ["", "## intent.domain (enum)", ""]
    for d in schema["properties"]["intent"]["properties"]["domain"]["enum"]:
        lines.append(f"- `{d}`")

    lines += ["", "## payload sub-objects", ""]
    for defname, defschema in schema["definitions"].items():
        if defschema.get("type") != "object":
            continue
        lines.append(f"### {defname}")
        lines.append("")
        lines.append(_fmt_props(defschema.get("properties", {}), set(defschema.get("required", []))))
        lines.append("")

    lines += [
        "## Enforcement guarantees encoded in this schema",
        "",
        f"- `FileOp.op` enum: `{schema['definitions']['FileOp']['properties']['op']['enum']}` — "
        "notice there is no `read`. There is no schema-valid way to ask this gateway for raw file content.",
        f"- `RetrievedChunk.content` has `maxLength: {schema['definitions']['RetrievedChunk']['properties']['content']['maxLength']}`.",
        f"- `CommandExec.capped` is `const: true` — a request that sets it to `false` fails validation before anything runs.",
        f"- `LogOp.tail_lines` maxes at `{schema['definitions']['LogOp']['properties']['tail_lines']['maximum']}`.",
        "",
        "See `docs/ENFORCEMENT.md` for how these constraints are enforced in code, not just declared.",
        "",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    OUT.write_text(generate())
    print(f"wrote {OUT}")
