from __future__ import annotations
import hashlib
import json
import os
from datetime import datetime, timezone
from pathlib import Path

_ENV_ROOT = os.environ.get("JFA_REPO_ROOT")
ROOT = Path(_ENV_ROOT) if _ENV_ROOT else Path(__file__).resolve().parent.parent
MANIFEST_PATH = ROOT / "index" / "manifest.json"

TRACKED_DIRS = ["gateway", "schema", "config", "retrieval", "daemons", "tools",
                "knowledge", "symbols", "index", "docs", "tests", ".github/workflows"]

SKIP_NAMES = {"manifest.json"}


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(65536), b""):
            h.update(block)
    return h.hexdigest()


def build_manifest(repo_root: Path | None = None) -> dict:
    """Content manifest of every tracked artifact: path, size, sha256.

    Deterministic (sorted by path); `generated_at` is the only moving field.
    Consumed by the manifest workflow to prove indexes match their sources.
    """
    repo_root = repo_root or ROOT
    entries = []
    for rel_dir in TRACKED_DIRS:
        base = repo_root / rel_dir
        if not base.is_dir():
            continue
        for path in sorted(base.rglob("*")):
            if not path.is_file() or path.name in SKIP_NAMES:
                continue
            if "__pycache__" in path.parts:
                continue
            entries.append({
                "path": str(path.relative_to(repo_root)),
                "bytes": path.stat().st_size,
                "sha256": _sha256(path),
            })
    entries.sort(key=lambda e: e["path"])

    kb_path = repo_root / "index" / "kb.index.json"
    sym_path = repo_root / "symbols" / "index.json"
    graph_path = repo_root / "knowledge" / "graph.json"

    def _count(path: Path, key: str, nested: str | None = None) -> int:
        if not path.exists():
            return 0
        data = json.loads(path.read_text())
        if nested:
            data = data.get(nested, {})
        return len(data.get(key, []))

    manifest = {
        "version": "1.1.0",
        "generated_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "generated_by": "gateway/manifest.py",
        "note": "Auto-generated by the manifest workflow. Never hand-edit.",
        "counts": {
            "files": len(entries),
            "kb_chunks": _count(kb_path, "chunks"),
            "symbols": _count(sym_path, "symbols"),
            "graph_nodes": _count(graph_path, "nodes", nested="graph"),
            "graph_edges": _count(graph_path, "edges", nested="graph"),
        },
        "files": entries,
    }
    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2) + "\n")
    return manifest


def main() -> int:
    m = build_manifest()
    c = m["counts"]
    print(f"manifest: {c['files']} files, {c['kb_chunks']} kb chunks, "
          f"{c['symbols']} symbols, {c['graph_nodes']} nodes, {c['graph_edges']} edges")
    print(f"-> {MANIFEST_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
